spring:
  cloud:
    gateway:
      routes:
        - id: myRoute
          uri: http://47.101.155.205:8090/
          predicates:
            - Path=/**
      metrics:
        enabled: true
  application:
    name: spring-cloud-gateway-simple
management:
  endpoints:
    web:
      exposure:
        include: ["metrics", "prometheus"]
  metrics:
    export:
      prometheus:
        enabled: true